version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  app:
    depends_on:
      - db
    build: .
    command: npm run start
    working_dir: /app
    environment:
      - DB_URL=db
    volumes:
      - .:/app
    links:
      - db
    ports:
      - '3000:3000'
